server:
  port: 9494

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB
fileType: image/jpeg,image/png
rootPath: /Users/shen/Desktop
subDir: /salves
maxSizeM: 10
maxNum: 5 